// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhvfudiyndqllrxzldrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhodmZ1ZGl5bmRxbGxyeHpsZHJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3ODE5OTksImV4cCI6MjA1MzM1Nzk5OX0.cOjPINXFjG26_y_ESs8fA2f7IOzbnK9F_aveTLEktBg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);